import type { BlogViBody } from "../blog-i18n";

export const part5: Record<string, BlogViBody> = {
  "ai-governance-enterprise-software-compliance-2026": {
    content: [
      "Năm 2026, AI đã hiện diện trong gần như mọi hệ thống phần mềm doanh nghiệp — từ chấm điểm khách hàng tiềm năng trong CRM, dự báo nhu cầu trong ERP, đến gợi ý nội dung trong CMS. đi kèm với sự phổ biến đó là trách nhiệm. Các cơ quan quản lý trên toàn thế giới đang triển khai các khung quản trị AI, và doanh nghiệp không tuân thủ đối mặt không chỉ với tiền phạt mà còn tổn hại danh tiếng và mất lòng tin của khách hàng.",
      "Đạo luật AI của EU (EU AI Act), đã có hiệu lực thi hành đầy đủ từ năm 2026, phân loại các hệ thống AI theo mức độ rủi ro và áp đặt các yêu cầu tương ứng với rủi ro đó. Các hệ thống rủi ro cao (bao gồm những hệ thống dùng trong nhân sự, tài chính và y tế) phải chứng minh tính minh bạch, giám sát của con người, chất lượng dữ liệu và tài liệu hóa đầy đủ. Các quy định tương tự cũng đang hình thành tại Mỹ, Singapore và Úc.",
      "Đối với các lãnh đạo công nghệ, điều này có nghĩa là quản trị AI không thể nữa là chuyện để suy nghĩ sau cùng. Nó phải được tích hợp vào vòng đời phát triển phần mềm ngay từ ngày đầu. Các thực hành chủ chốt bao gồm: duy trì tài liệu và phiên bản hóa mô hình, triển khai tính năng giải trình để người dùng hiểu được các quyết định của AI, thiết lập quy trình con người duyệt lại các quyết định tự động có rủi ro cao, và định kỳ kiểm toán thiên lệch trên dữ liệu huấn luyện cũng như kết quả đầu ra của mô hình.",
      "Triển khai kỹ thuật mới là điều quan trọng. Quản trị AI không chỉ là bài toán chính sách. Nó đòi hỏi đầu tư về kỹ thuật. Audit trail phải ghi lại mọi dự đoán của mô hình, dữ liệu đầu vào được sử dụng và điểm tin cậy. Feature store cần theo dõi nguồn gốc dữ liệu (data lineage). Model registry cần áp dụng quy trình phê duyệt trước khi triển khai lên production. Đây là những quyết định hạ tầng mà việc xây dựng ngay từ đầu dễ dàng hơn nhiều so với cải tạo về sau.",
      "Lập luận kinh doanh cho quản trị AI rất rõ ràng: nó giảm thiểu rủi ro, xây dựng lòng tin của khách hàng và tạo lợi thế cạnh tranh. Các công ty chứng minh được mình thực hành AI có trách nhiệm thắng nhiều hợp đồng hơn, đặc biệt trong các ngành bị điều tiết. Một khảo sát Deloitte năm 2026 cho thấy 78% khách hàng doanh nghiệp coi quản trị AI là một trong ba yếu tố hàng đầu khi đánh giá nhà cung cấp phần mềm. Để tìm hiểu thêm về các ứng dụng AI thực tế trong phần mềm doanh nghiệp, xem bài viết của chúng tôi về [vai trò của AI trong phần mềm doanh nghiệp hiện đại](/blog/vai-tro-cua-ai-trong-phan-mem-doanh-nghiep-hien-dai).",
      "Tại Retech Solutions, chúng tôi xây dựng quản trị AI vào mọi hệ thống mà chúng tôi phát triển. Các [giải pháp CMS, CRM và ERP](/services) của chúng tôi bao gồm audit trail khả năng cấu hình, phân quyền truy cập tính năng AI theo vai trò, và khả năng tài liệu hóa tích hợp sẵn giúp khách hàng đáp ứng yêu cầu tuân thủ mà không đánh đổi tốc độ và trí thông minh mà các tính năng AI hiện đại mang lại.",
    ],
    headings: [
      { id: "eu-ai-act-2026", text: "Đạo luật AI của EU trong năm 2026" },
      { id: "governance-development-lifecycle", text: "Quản trị trong Vòng đời Phát triển" },
      { id: "technical-implementation", text: "Triển khai Kỹ thuật của Quản trị AI" },
      { id: "business-case-governance", text: "Lập luận Kinh doanh cho Quản trị AI" },
    ],
  },
  "how-small-businesses-leverage-ai-without-breaking-bank": {
    content: [
      "Trí tuệ nhân tạo vốn có tiếng là đắt đỏ, phức tạp và chỉ dành cho các công ty Fortune 500 sở hữu đội data science riêng. Cái tiếng đó đã lỗi thời. Năm 2026, một hệ sinh thái ngày càng phong phú các công cụ AI giá cả phải chăng, dạng plug-and-play cho phép doanh nghiệp nhỏ tự động hóa quy trình, tương tác với khách hàng và ra quyết định dựa trên dữ liệu mà không cần viết một dòng code nào hay cam kết hợp đồng phần mềm trị giá sáu con số. Điều quan trọng là biết bắt đầu từ đâu và công cụ nào mang lại ROI thực sự so với khoản đầu tư.",
      "AI hướng tới khách hàng là mục tiêu dễ đạt nhất. Các nền tảng chatbot như Intercom Fin, Tidio và Drift hiện cung cấp agent hội thoại chạy bằng AI tự động xử lý tới 70% câu hỏi của khách hàng: trả lời FAQ, xử lý đổi trả và đặt lịch quanh đồng hồ. Các công cụ này có giá từ $30 đến $150 mỗi tháng và tích hợp trực tiếp với website, WhatsApp và các kênh mạng xã hội của bạn. Với một doanh nghiệp nhỏ đang dành hàng giờ mỗi ngày trả lời các câu hỏi lặp đi lặp lại, riêng khoản thời gian tiết kiệm đã đủ bù đắp chi phí ngay trong tháng đầu tiên.",
      "Tự động hóa marketing đã được tiếp sức bởi generative AI. Các công cụ như Mailchimp AI, Jasper và Copy.ai giúp các đội nhỏ tạo chiến dịch email, bài đăng mạng xã hội và nội dung blog ở quy mô lớn. Thay vì thuê copywriter hay dành cả buổi tối viết newsletter, bạn có thể tạo bản nháp hoàn chỉnh trong vài phút rồi tinh chỉnh theo tiếng nói thương hiệu của mình. Kết hợp thêm với phân khúc email bằng AI phân tích tỷ lệ mở và hành vi tương tác, bạn sẽ có một cỗ máy marketing mạnh vượt xa quy mô của mình.",
      "Phân tích và business intelligence từng đòi hỏi một analyst chuyên trách hoặc các nền tảng đắt đỏ như Tableau. Ngày nay, các công cụ như Google Analytics 4 kèm AI Insights, Microsoft Clarity, cùng các nền tảng BI giá dễ chịu như Metabase mang cho doanh nghiệp nhỏ khả năng tiếp cận phân tích dự đoán, heatmap hành vi người dùng và dashboard báo cáo tự động. Việc hiểu sản phẩm nào đang thịnh hành, kênh marketing nào chuyển đổi tốt nhất và khách hàng rơi rụng ở đâu trong phễu bán hàng không còn là xa xỉ. Nó nằm trong tầm với của bất kỳ doanh nghiệp nào sẵn sàng đầu tư vài giờ thiết lập.",
      "Chiến lược hiệu quả nhất cho doanh nghiệp nhỏ là áp dụng từng bước. Bắt đầu với một công cụ tác động cao, chi phí thấp (thường là chatbot hoặc nền tảng tự động hóa email) và đo lường kết quả trong 60 ngày. Khi thấy ROI rõ ràng, mới bổ sung công cụ tiếp theo. Tránh cái bẫy đăng ký đồng thời năm nền tảng AI mà không dùng hiệu quả cái nào. Hãy tập trung giải quyết vấn đề cụ thể: giảm thời gian phản hồi, tăng tỷ lệ mở email, hoặc cắt giảm số giờ dành cho nhập liệu thủ công. Để nhìn rộng hơn về tác động của AI tới phát triển phần mềm, hãy đọc [AI đang thay đổi phát triển phần mềm theo yêu cầu như thế nào](/blog/ai-dang-thay-doi-phat-trien-phan-mem-theo-yeu-cau).",
      "Tại Retech Solutions, chúng tôi giúp các doanh nghiệp nhỏ và vừa tích hợp AI vào [hệ thống CMS, CRM và ERP](/services) hiện có của họ. Cho dù bạn cần một chatbot tùy chỉnh được huấn luyện trên tài liệu sản phẩm, một pipeline báo cáo tự động, hay một engine gợi ý nội dung bằng AI cho website, chúng tôi xây dựng giải pháp vừa túi tiền và lớn lên cùng doanh nghiệp của bạn. Bạn không cần ngân sách doanh nghiệp lớn để sở hữu trí thông minh hạng doanh nghiệp.",
    ],
    headings: [
      { id: "customer-facing-ai-tools", text: "Công cụ AI Hướng khách hàng Tự hoàn vốn" },
      { id: "marketing-automation-generative-ai", text: "Tự động hóa Marketing Với Generative AI" },
      { id: "analytics-business-intelligence", text: "Phân tích và Business Intelligence Giá dễ chịu" },
      { id: "incremental-adoption-strategy", text: "Chiến lược Áp dụng Từng bước" },
    ],
  },
  "rise-of-edge-computing-what-it-means-for-web-applications": {
    content: [
      "Hơn một thập kỷ qua, ứng dụng web vận hành theo một mô hình đơn giản: người dùng ở Tokyo gửi một request, nó du hành đến data center ở Virginia, được xử lý, rồi phản hồi quay trở lại. Chu trình này cộng thêm hàng trăm mili-giây độ trễ mà người dùng cảm nhận là sự chậm chạp. Edge computing xóa bỏ nút thắt cổ chai này bằng cách thực thi logic ứng dụng tại các server đặt gần người dùng về mặt vật lý — trong một số trường hợp ngay tại cùng thành phố. Năm 2026, edge computing đã đi từ một kỹ thuật tối ưu nhỏ lẻ trở thành lựa chọn kiến trúc chủ lưu, định hình lại cách ứng dụng web được xây dựng và phân phối.",
      "Sự dịch chuyển quyết định là bước tiến từ CDN truyền thống sang nền tảng edge compute. Các CDN như Cloudflare và Akamai ban đầu chỉ cache nội dung tĩnh (hình ảnh, CSS, JavaScript) tại các điểm hiện diện (PoP) khắp thế giới. Điều này giảm độ trễ cho nội dung tĩnh, nhưng mọi request động vẫn phải đi về origin server. Edge computing tiến thêm một bước bằng cách chạy chính mã ứng dụng tại những PoP đó. Cloudflare Workers, Vercel Edge Functions, Deno Deploy và AWS CloudFront Functions giờ cho phép developer triển khai serverless function thực thi trong bán kính vài mili-giây của người dùng, bất kể hạ tầng origin đặt ở đâu.",
      "Mức cải thiện độ trễ mang tính bước ngoặt và đo lường được. Một request API render phía server từ Đông Nam Á đến server đặt tại Mỹ thường mất 200-400 mili-giây. Cùng request đó được xử lý tại một edge node ở Singapore chỉ mất 10-30 mili-giây. Với các ứng dụng thời gian thực (dashboard, công cụ cộng tác, thanh khoản thương mại điện tử), khoảng cách này chính là ranh giới giữa một trải nghiệm phản hồi nhanh và một trải nghiệm tưởng như bị hỏng. Nghiên cứu của Google cho thấy cứ mỗi 100ms tăng thêm độ trễ làm giảm tỷ lệ chuyển đổi tới 7%, biến edge computing thành đòn bẩy doanh thu trực tiếp cho các ứng dụng nhạy cảm với hiệu suất.",
      "Xác thực và cá nhân hóa là những use case đắt giá nhất của edge function. Thay vì chuyển hướng người dùng về origin server để xác minh JWT token và tra cứu tùy chọn, edge function có thể validate token, đọc ngữ cảnh người dùng từ một kho dữ liệu truy cập được từ edge như Cloudflare KV hoặc Upstash Redis, và cá nhân hóa phản hồi trước khi nó kịp chạm tới origin. Điều này cho phép A/B testing tức thì, nội dung theo vị trí địa lý và bố cục được cá nhân hóa mà không phải trả giá bằng độ trễ của một chu kỳ khứ hồi tới server.",
      "Tuy nhiên, edge computing không phải là giải pháp thay thế toàn diện cho hạ tầng server truyền thống. Edge function có những giới hạn: thời gian thực thi hạn chế, truy cập hạn chế vào hệ thống tệp và các kết nối dài hạn, và giới hạn bộ nhớ nhỏ hơn. Chúng xuất sắc trong định tuyến request, xác thực, chuyển đổi nội dung và cá nhân hóa, nhưng logic nghiệp vụ phức tạp, tính toán nặng và các thao tác dồn dập vào database vẫn phù hợp hơn với application server chuyên dụng. Kiến trúc hiệu quả nhất năm 2026 là mô hình lai, trong đó edge function đảm nhận lớp ngoài nhạy cảm về độ trễ còn origin server gánh lớp trong nặng về tính toán. Để tìm hiểu thêm về kiến trúc khả mở, xem [hướng dẫn xây dựng ứng dụng web khả mở](/blog/xay-dung-ung-dung-web-kha-mo-phan-tich-ky-thuat) của chúng tôi.",
      "Tại Retech Solutions, chúng tôi thiết kế ứng dụng web tận dụng edge computing ở nơi nó mang lại giá trị nhiều nhất. Cho dù là xây dựng một [CMS lưu lượng cao](/services/cms-platforms) phân phối nội dung được cá nhân hóa cho người dùng khắp châu Á, một dashboard phân tích thời gian thực cần thời gian phản hồi dưới 50ms, hay một nền tảng thương mại điện tử nơi mỗi mili-giây tốc độ thanh khoản đều quy đổi thành doanh thu, chúng tôi thiết kế sự kết hợp đúng đắn giữa hạ tầng edge và origin cho từng yêu cầu dự án.",
    ],
    headings: [
      { id: "cdn-to-edge-evolution", text: "Từ CDN đến Nền tảng Edge Compute" },
      { id: "latency-improvements", text: "Cải thiện Độ trễ Đo lường được" },
      { id: "authentication-personalization", text: "Xác thực và Cá nhân hóa tại Edge" },
      { id: "edge-vs-server", text: "Khi nào Dùng Edge, khi nào Dùng Server" },
    ],
  },
  "why-typescript-became-default-enterprise-development": {
    content: [
      "Năm 2026, TypeScript không còn là lựa chọn thay thế. Nó đã thành mặc định. Khảo sát State of JavaScript mới nhất cho biết hơn 82% developer chuyên nghiệp thường xuyên sử dụng TypeScript, và mọi framework doanh nghiệp lớn — Next.js, Angular, NestJS, React — đều lấy TypeScript làm ngôn ngữ chính. Đây không phải xu hướng chạy theo hype. Đây là bước chuyển thực dụng, được thúc đẩy bởi những cải thiện đo lường được về chất lượng code, năng suất developer và khả năng cộng tác trong nhóm — những hiệu ứng càng rõ nét trong các dự án doanh nghiệp quy mô lớn.",
      "Các con số kể một câu chuyện thuyết phục. Báo cáo Octoverse 2025 của GitHub cho thấy TypeScript vượt JavaScript để trở thành ngôn ngữ được dùng nhiều nhất trên nền tảng này tính theo số repository. Khảo sát developer của Stack Overflow liên tục xếp TypeScript trong nhóm năm ngôn ngữ được yêu thích nhất. Và quan trọng hơn với các nhà ra quyết định doanh nghiệp, nhiều nghiên cứu nội bộ từ các công ty như Slack, Asana và Airbnb ghi nhận lượng bug production giảm 15-25% sau khi áp dụng TypeScript, với cải thiện đáng kể nhất ở độ tin cậy khi refactor và việc thực thi API contract.",
      "Lợi ích cho các đội lớn mới là nơi TypeScript thực sự tỏa sáng. Trong môi trường doanh nghiệp nơi hàng chục developer cùng chạm vào một codebase, các type annotation đóng vai trò như tài liệu sống luôn đồng bộ với code thực tế. Khi một kỹ sư backend thay đổi cấu trúc phản hồi của API, trình biên dịch TypeScript lập tức chỉ ra mọi phía frontend sẽ bị lỗi — trước khi code kịp lên staging, chưa nói đến production. Lưới an toàn lúc biên dịch này cắt giảm chi phí phối hợp vốn thường làm chậm các đội lớn, và khiến các phụ thuộc liên nhóm trở nên dễ quản lý mà không cần họp hành liên tục.",
      "Việc di chuyển từ JavaScript sang TypeScript giờ đã được ghi chép đầy đủ và rủi ro thấp. Cách tiếp cận chuẩn là từng bước: đổi tên file từ .js sang .ts (hoặc .jsx sang .tsx), bật strict mode dần dần, và chuyển đổi từng module một. Các công cụ như ts-migrate tự động hóa phần chuyển đổi cơ học, chèn type assertion ở những chỗ trình biên dịch không thể tự suy luận kiểu. Đa số các đội báo cáo hoàn tất di chuyển một ứng dụng cỡ trung trong 2-4 tuần với thời gian chết bằng không. Điều then chốt là bắt đầu từ các thư viện tiện ích dùng chung và các kiểu tại biên API (những nơi kiểu sai gây hại lớn nhất) rồi mở rộng độ phủ từ đó.",
      "Hệ sinh thái TypeScript đã đạt quy mô tới hạn. Mọi thư viện và framework lớn đều phân phối type definition hạng nhất. Kho DefinitelyTyped, dù vẫn hoạt động, ngày càng trở nên không cần thiết khi các tác giả package đã kèm type sẵn trong package. Hỗ trợ công cụ toàn diện: VS Code, WebStorm và Neovim đều cung cấp tự động hoàn thành thông minh, tô sáng lỗi ngay tại chỗ và refactor tự động chạy trên TypeScript Language Server. Các công cụ build như esbuild, Vite và Turbopack xử lý biên dịch TypeScript ở tốc độ gần-native, xóa bỏ hình phạt thời gian build từng làm chậm giai đoạn đầu của việc áp dụng. Để được hỗ trợ chọn stack phù hợp, xem hướng dẫn của chúng tôi về [cách chọn đúng tech stack cho dự án tiếp theo](/blog/chon-tech-stack-phu-hop-du-an-tiep-theo).",
      "Tại Retech Solutions, TypeScript là ngôn ngữ mặc định cho mọi dự án mới và là lựa chọn được khuyến nghị cho khách hàng doanh nghiệp đang đánh giá technology stack của mình. Đội ngũ chúng tôi xây dựng [giải pháp CMS, CRM và ERP theo yêu cầu](/services) bằng TypeScript, hưởng lợi từ type safety chặt chẽ hơn, hỗ trợ IDE tốt hơn và codebase dễ bảo trì hơn. Với các doanh nghiệp đang có ứng dụng JavaScript, chúng tôi cung cấp dịch vụ di chuyển có cấu trúc, chuyển đổi codebase từng phần với tối thiểu gián đoạn cho quá trình phát triển đang diễn ra.",
    ],
    headings: [
      { id: "adoption-statistics", text: "Mức độ Áp dụng TypeScript qua Con số" },
      { id: "benefits-large-teams", text: "Lợi ích cho Các đội Kỹ thuật Lớn" },
      { id: "migration-strategies", text: "Chiến lược Di chuyển Từ JavaScript đã được Chứng minh" },
      { id: "ecosystem-maturity", text: "Độ trưởng thành của Hệ sinh thái và Công cụ" },
    ],
  },
  "building-accessible-websites-practical-guide-2026": {
    content: [
      "Khả năng tiếp cận web (accessibility) không còn là điều \"có thì tốt\". Đó là yêu cầu mang tính pháp lý, đạo đức và kinh doanh. Năm 2026, hơn 1,3 tỷ người trên thế giới sống cùng một dạng khuyết tật nào đó, và dân số toàn cầu già hóa khiến con số này không ngừng tăng. Web Content Accessibility Guidelines (WCAG) 2.2, phát hành cuối năm 2025, đưa ra chín tiêu chí thành công mới nhằm khắc phục các lỗ hổng về accessibility trên di động, rào cản xác thực và xử lý focus. Với developer và doanh nghiệp, cập nhật theo các tiêu chuẩn này là điều thiết yếu để tiếp cận trọn vẹn tệp khán giả, tránh rủi ro pháp lý và xây dựng sản phẩm số dùng được cho tất cả mọi người.",
      "Những cải thiện accessibility tác động lớn nhất lại là những thứ đơn giản nhất để triển khai. HTML ngữ nghĩa (semantic HTML) là nền móng: dùng các thẻ heading (h1 đến h6) theo đúng thứ bậc, gắn nhãn rõ ràng cho các trường form bằng phần tử label, dùng button cho các điều khiển tương tác thay vì div được trang trí, và cung cấp alt text cho mọi hình ảnh có ý nghĩa. Điều hướng bằng bàn phím phải hoạt động với mọi phần tử tương tác: người dùng không thể dùng chuột phải có thể truy cập và vận hành mọi điều khiển bằng Tab, Enter, Space và các phím mũi tên. Focus indicator phải hiển thị rõ ràng với độ tương phản cao; việc xóa kiểu outline mà không cung cấp phương án thay thế là một trong những sai sót accessibility phổ biến và gây hại nhất.",
      "WCAG 2.2 đưa vào một số tiêu chí mà developer cần xử lý. Success Criterion 2.4.11 (Focus Appearance) yêu cầu focus indicator đáp ứng yêu cầu tối thiểu về kích thước và độ tương phản, chấm dứt kỷ nguyên của vòng focus gần như vô hình. Tiêu chí 3.2.6 (Consistent Help) yêu cầu các cơ chế hỗ trợ như chat hỗ trợ và thông tin liên hệ xuất hiện ở cùng thứ tự tương đối trên mọi trang. Tiêu chí 3.3.7 (Redundant Entry) cấm yêu cầu người dùng nhập lại thông tin họ đã cung cấp trong cùng một quy trình. Những thay đổi này phản ánh sự dịch chuyển về các yêu cầu thực dụng, lấy người dùng làm trung tâm — giảm ma sát cho tất cả mọi người, không riêng người dùng khuyết tật.",
      "Các công cụ kiểm thử đã trưởng thành đáng kể và nên được tích hợp vào mọi quy trình phát triển. Axe DevTools của Deque cung cấp kiểm tra accessibility tự động ngay trong trình duyệt và có thể chạy trong pipeline CI/CD để ngăn hồi quy. Lighthouse bao gồm điểm số accessibility đánh giá các vấn đề phổ biến. Playwright và Cypress hỗ trợ các assertion accessibility tự động chạy song song với kiểm thử chức năng. Tuy nhiên, công cụ tự động chỉ phát hiện được 30-40% các vấn đề accessibility. Việc kiểm thử thủ công với trình đọc màn hình (NVDA trên Windows, VoiceOver trên macOS và iOS), điều hướng chỉ bằng bàn phím, và kiểm thử thu phóng ở mức 200% vẫn là thiết yếu để bắt những vấn đề quan trọng nhất với người dùng thực.",
      "Lập luận kinh doanh cho accessibility chưa bao giờ mạnh như hiện tại. Website accessible tiếp cận thêm 15-20% người dùng, cải thiện hiệu suất SEO nhờ cấu trúc ngữ nghĩa tốt hơn, và thể hiện trách nhiệm xã hội của doanh nghiệp. Rủi ro pháp lý là thực và đang gia tăng: các vụ kiện accessibility web theo Americans with Disabilities Act (ADA) và European Accessibility Act tăng đều qua từng năm, với chi phí dàn xếp trung bình vượt $50.000. Đầu tư chủ động cho accessibility chỉ bằng một phần nhỏ chi phí kiện tụng và khắc phục bị động. Các công ty như Apple, Microsoft và Shopify đã chứng minh accessibility có thể là điểm khác biệt của thương hiệu chứ không phải một ô đánh dấu tuân thủ. Để tìm hiểu các thực hành UI/UX doanh nghiệp tốt nhất, xem hướng dẫn của chúng tôi về [điều gì tạo nên thiết kế UI/UX tuyệt vời cho phần mềm doanh nghiệp](/blog/nguyen-tac-ui-ux-cho-phan-mem-doanh-nghiep).",
      "Tại Retech Solutions, chúng tôi đưa accessibility vào mọi dự án ngay từ giai đoạn thiết kế. Các [giải pháp CMS, CRM và ERP](/services) của chúng tôi tuân theo tiêu chuẩn WCAG 2.2 AA theo mặc định, với markup ngữ nghĩa, điều hướng bàn phím, tương thích trình đọc màn hình và độ tương phản màu đầy đủ được tích hợp sẵn trong từng component. Chúng tôi tiến hành kiểm tra accessibility tự động và thủ công trước khi ra mắt, cùng giám sát liên tục để đảm bảo tuân thủ khi nội dung và tính năng thay đổi. Accessibility không phải một phần bổ sung. Đó là một thuộc tính chất lượng nền tảng của phần mềm chuyên nghiệp.",
    ],
    headings: [
      { id: "foundational-techniques", text: "Các Kỹ thuật Nền tảng Mọi Developer cần Biết" },
      { id: "wcag-22-updates", text: "Điểm mới trong WCAG 2.2" },
      { id: "testing-tools-workflow", text: "Công cụ Kiểm thử và Tích hợp Quy trình" },
      { id: "business-case-accessibility", text: "Lập luận Kinh doanh cho Accessibility" },
    ],
  },
};
